# Don't print a new line at the start of the prompt
add_newline = true

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[aws]
symbol = " "

[golang]
symbol = " "

#
#
# default_prompt_order = [
#     "username",
#     "directory",
#     "git_branch",
#     "git_status",
#     "package",
#     "nodejs",
#     "ruby",
#     "rust",
#     "python",
#     "golang",
#     "cmd_duration",
#     "line_break",
#     "jobs",
#     "battery",
#     "character",
# ]
